"""empty message

Revision ID: be4e1175f386
Revises: 
Create Date: 2018-06-08 07:32:23.259824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4e1175f386'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=40), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('visitante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=70), nullable=False),
    sa.Column('empresa', sa.String(length=70), nullable=False),
    sa.Column('telefone', sa.String(length=70), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('foto', sa.String(length=70), nullable=False),
    sa.Column('documento', sa.String(length=70), nullable=False),
    sa.Column('motivo', sa.String(length=70), nullable=False),
    sa.Column('cracha', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitante')
    op.drop_table('users')
    # ### end Alembic commands ###
